# примеры API-запросов

# получение объявлений
GET 127.0.0.1:8000/api/v1/orders/?products=Tea
Content-Type: application/json
Authorization: Token a41edf735ef52515ceb35a0f3021ae3011743461

###
# создание объявления
POST 127.0.0.1:8000/api/v1/orders/
Content-Type: application/json
Authorization: Token 5d0a3e97adb8d302f9366c9dd962c774bfbfd944

{
  "positions": [
    {"product_id": 4, "quantity": 1}
  ]
}

###

GET 127.0.0.1:8000/api/v1/products/
Content-Type: application/json
Authorization: Token a41edf735ef52515ceb35a0f3021ae3011743461

###

POST 127.0.0.1:8000/api/v1/reviews/
Content-Type: application/json
Authorization: Token 5d0a3e97adb8d302f9366c9dd962c774bfbfd944

{
  "review": 4,
  "text": "review for cofe",
  "mark": 6
}

###

GET 127.0.0.1:8000/api/v1/reviews/
Content-Type: application/json
Authorization: Token a41edf735ef52515ceb35a0f3021ae3011743461

###

# попытка поменять объявление
PATCH 127.0.0.1:8000/api/advertisements/25/
Content-Type: application/json
Authorization: Token 90c3941909c5d6cceade814470f74efbfc65d6f8

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET 127.0.0.1:8000/api/advertisements/?status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET 127.0.0.1:8000/api/advertisements/?created_at_before=2019-10-01
Content-Type: application/json

###
