# примеры API-запросов

# получение заказов
GET 127.0.0.1:8000/api/v1/orders/
Content-Type: application/json
Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

###
#фильтрация заказов по статусу и наименованию товаров
GET 127.0.0.1:8000/api/v1/orders/?status=Done&products=Tea
Content-Type: application/json
Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

###
# создание заказа
POST 127.0.0.1:8000/api/v1/orders/
Content-Type: application/json
Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

{
  "positions": [
    {"product_id": 6, "quantity": 2},
    {"product_id": 7, "quantity": 2},
    {"product_id": 8, "quantity": 2},
    {"product_id": 9, "quantity": 4}
  ]
}

###
#удаление товара с ИД=5
DELETE 127.0.0.1:8000/api/v1/products/6/
Content-Type: application/json
Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

###
#получение всех товаров
GET 127.0.0.1:8000/api/v1/products/
Content-Type: application/json
#Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

###
#фильтрация товаров по цене и названию
GET 127.0.0.1:8000/api/v1/products/?price_from=100&name=limon
Content-Type: application/json
#Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

###
#создание товара
POST 127.0.0.1:8000/api/v1/products/
Content-Type: application/json
Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

{
  "name": "limon",
  "desc": "desc for limon",
  "price": 200
}

###
#создание отзыва
POST 127.0.0.1:8000/api/v1/reviews/
Content-Type: application/json
Authorization: Token 5d0a3e97adb8d302f9366c9dd962c774bfbfd944

{
  "review": 10,
  "text": "review for limon",
  "mark": 2
}

###
#получение всех отзывов
GET 127.0.0.1:8000/api/v1/reviews/
Content-Type: application/json
#Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

###
#фильтрация отзывов !!!!!!!
GET 127.0.0.1:8000/api/v1/reviews/?review=7
Content-Type: application/json
Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

###

#обновление отзыва
PATCH 127.0.0.1:8000/api/v1/reviews/52/
Content-Type: application/json
Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

{
  "mark": 3
}

###
#получение всех подборок
GET 127.0.0.1:8000/api/v1/collections/
Content-Type: application/json
#Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

###
#создание подборки
POST 127.0.0.1:8000/api/v1/collections/
Content-Type: application/json
Authorization: Token 29e07421a0aa6d49dc35a6c5c05aa2b3891d2079

{
  "title": "collections_2",
  "text": "colcolcol",
  "products": [
    6,
    8,
    7
  ]
}

###