# Generated by Django 3.1.2 on 2020-11-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20201120_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorderposition',
            old_name='quantiity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default='description for product', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productorderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.product'),
        ),
    ]
