# Generated by Django 3.1.2 on 2020-11-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_orders_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='title',
        ),
    ]
