# Generated by Django 3.1.2 on 2020-11-26 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_remove_orders_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.product'),
        ),
    ]
