# Generated by Django 3.1.2 on 2020-11-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_sum',
        ),
    ]
