# Generated by Django 3.1.2 on 2020-12-03 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0012_remove_orders_order_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productreviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='collections',
            name='products',
            field=models.ManyToManyField(to='magazine.Product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(through='magazine.ProductOrderPosition', to='magazine.Product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('In_progress', 'Выполняется'), ('Done', 'Готов')], default='New', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productorderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='magazine.orders', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productorderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='productorderposition',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='mark',
            field=models.PositiveIntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='magazine.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Отзыв'),
        ),
    ]
